[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

lib_deps =
    ZinggJM/GxEPD2@^1.5.12
    adafruit/Adafruit GFX Library@^1.11.7

upload_port = COM3  ; Replace with your ESP32 COM port
upload_speed = 115200